package rpc

import (
	"encoding/json"
	"fmt"
	"net/http"
	"os"
	"strings"
	"time"
)

type setupConfig struct {
	ChainID          string `json:"chainId"`
	NetworkName      string `json:"networkName"`
	NodeMode         string `json:"nodeMode"`
	BlockTime        string `json:"blockTime"`
	WalletAddress    string `json:"walletAddress"`
	WalletKey        string `json:"walletKey"`
	ValidatorKey     string `json:"validatorKey"`
	RPCPort          string `json:"rpcPort"`
	WSPort           string `json:"wsPort"`
	P2PPort          string `json:"p2pPort"`
	P2PAdvertiseHost string `json:"p2pAdvertiseHost"`
	MaxPeers         string `json:"maxPeers"`
	BootstrapNodes   string `json:"bootstrapNodes"`
	DataDir          string `json:"dataDir"`
	StorageLimitGB   string `json:"storageLimitGb"`
	EnableFirewall   string `json:"enableFirewall"`
	EnableFail2ban   string `json:"enableFail2ban"`
	SSHPort          string `json:"sshPort"`
	AllowedIPs       string `json:"allowedIps"`
	LogLevel         string `json:"logLevel"`
	LogFormat        string `json:"logFormat"`
	DashboardPin     string `json:"dashboardPin"`
}

// envSetting writes a shell-compatible .env assignment. Setup values such as
// network names and data paths may contain spaces; leaving them unquoted makes
// `source .env` execute the trailing words as commands.
func envSetting(key, value string) string {
	value = strings.ReplaceAll(value, "'", "'\\''")
	return fmt.Sprintf("%s='%s'", key, value)
}

func (s *Server) handleSetupPage(w http.ResponseWriter, r *http.Request) {
	f, err := staticFiles.Open("static/setup.html")
	if err != nil {
		http.Error(w, "setup page unavailable", http.StatusNotFound)
		return
	}
	defer f.Close()
	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	buf := make([]byte, 32*1024)
	for {
		n, err := f.Read(buf)
		if n > 0 {
			w.Write(buf[:n])
		}
		if err != nil {
			break
		}
	}
}

func (s *Server) handleSetupStatus(w http.ResponseWriter, r *http.Request) {
	_, err := os.Stat(".env")
	configured := err == nil
	jsonOK(w, map[string]interface{}{
		"configured": configured,
		"height":     s.chain.Height(),
		"pinSet":     s.auth.PinIsSet(),
	})
}

func (s *Server) handleGuidesPage(w http.ResponseWriter, r *http.Request) {
	f, err := staticFiles.Open("static/guides.html")
	if err != nil {
		http.Error(w, "guides page unavailable", http.StatusNotFound)
		return
	}
	defer f.Close()
	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	buf := make([]byte, 32*1024)
	for {
		n, err := f.Read(buf)
		if n > 0 {
			w.Write(buf[:n])
		}
		if err != nil {
			break
		}
	}
}

func (s *Server) handleSetupApply(w http.ResponseWriter, r *http.Request) {
	var cfg setupConfig
	if err := json.NewDecoder(r.Body).Decode(&cfg); err != nil {
		jsonErr(w, http.StatusBadRequest, "invalid JSON: "+err.Error())
		return
	}

	def := func(v, d string) string {
		if strings.TrimSpace(v) == "" {
			return d
		}
		return strings.TrimSpace(v)
	}

	cfg.ChainID = def(cfg.ChainID, "198282")
	cfg.NetworkName = def(cfg.NetworkName, "GYDS Chain")
	cfg.NodeMode = def(cfg.NodeMode, "full")
	cfg.BlockTime = def(cfg.BlockTime, "120")
	cfg.RPCPort = def(cfg.RPCPort, "8545")
	cfg.WSPort = def(cfg.WSPort, "8546")
	cfg.P2PPort = def(cfg.P2PPort, "30303")
	cfg.MaxPeers = def(cfg.MaxPeers, "25")
	cfg.DataDir = def(cfg.DataDir, "./data")
	cfg.StorageLimitGB = def(cfg.StorageLimitGB, "50")
	cfg.EnableFirewall = def(cfg.EnableFirewall, "true")
	cfg.EnableFail2ban = def(cfg.EnableFail2ban, "true")
	cfg.SSHPort = def(cfg.SSHPort, "22")
	cfg.LogLevel = def(cfg.LogLevel, "info")
	cfg.LogFormat = def(cfg.LogFormat, "json")

	pin := strings.TrimSpace(cfg.DashboardPin)
	if pin != "" && (len(pin) < pinMinLen || len(pin) > pinMaxLen) {
		jsonErr(w, http.StatusBadRequest,
			fmt.Sprintf("dashboard PIN must be %d–%d characters", pinMinLen, pinMaxLen))
		return
	}

	ts := time.Now().UTC().Format("2006-01-02T15:04:05Z")

	var sb strings.Builder
	w1 := func(s string) { sb.WriteString(s + "\n") }

	w1("# ══════════════════════════════════════════════════════════════════")
	w1("#  GYDS Chain Full Node — Environment Configuration")
	w1(fmt.Sprintf("#  Generated by setup wizard: %s", ts))
	w1("# ══════════════════════════════════════════════════════════════════")
	w1("")
	w1("# ── Chain Identity ─────────────────────────────────────────────")
	w1(envSetting("GYDS_CHAIN_ID", cfg.ChainID))
	w1(envSetting("GYDS_NETWORK_NAME", cfg.NetworkName))
	w1(envSetting("GYDS_NODE_MODE", cfg.NodeMode))
	w1(envSetting("GYDS_BLOCK_TIME", cfg.BlockTime))
	w1("")
	w1("# ── Wallet ─────────────────────────────────────────────────────")
	w1(envSetting("GYDS_WALLET_ADDRESS", cfg.WalletAddress))
	w1(envSetting("GYDS_WALLET_PRIVATE_KEY", cfg.WalletKey))
	if strings.TrimSpace(cfg.ValidatorKey) != "" {
		w1(envSetting("GYDS_VALIDATOR_KEY", cfg.ValidatorKey))
	} else {
		w1("# GYDS_VALIDATOR_KEY=")
	}
	w1("")
	w1("# ── RPC / API Ports ────────────────────────────────────────────")
	w1(envSetting("GYDS_RPC_PORT", cfg.RPCPort))
	w1("GYDS_RPC_HOST=0.0.0.0")
	w1(envSetting("GYDS_WS_PORT", cfg.WSPort))
	w1("")
	w1("# ── P2P Networking ─────────────────────────────────────────────")
	w1(envSetting("GYDS_P2P_PORT", cfg.P2PPort))
	if strings.TrimSpace(cfg.P2PAdvertiseHost) != "" {
		w1(envSetting("GYDS_P2P_ADVERTISE_HOST", cfg.P2PAdvertiseHost))
	} else {
		w1("# GYDS_P2P_ADVERTISE_HOST=")
	}
	w1(envSetting("GYDS_MAX_PEERS", cfg.MaxPeers))
	if strings.TrimSpace(cfg.BootstrapNodes) != "" {
		w1(envSetting("GYDS_BOOTSTRAP_NODES", cfg.BootstrapNodes))
	} else {
		w1("# GYDS_BOOTSTRAP_NODES=")
	}
	w1("")
	w1("# ── Storage ────────────────────────────────────────────────────")
	w1(envSetting("GYDS_DATA_DIR", cfg.DataDir))
	w1(envSetting("GYDS_STORAGE_LIMIT_GB", cfg.StorageLimitGB))
	w1("")
	w1("# ── Firewall & Security ────────────────────────────────────────")
	if pin != "" {
		w1("# Dashboard PIN is also stored here for easy node reconfiguration.")
		w1("# Keep this file mode 0600 and remove the value after the node is initialized if desired.")
		w1(envSetting("GYDS_DASHBOARD_PIN", pin))
	} else {
		w1("# GYDS_DASHBOARD_PIN=")
	}
	w1(envSetting("GYDS_ENABLE_FIREWALL", cfg.EnableFirewall))
	w1(envSetting("GYDS_ENABLE_FAIL2BAN", cfg.EnableFail2ban))
	w1(envSetting("GYDS_SSH_PORT", cfg.SSHPort))
	if strings.TrimSpace(cfg.AllowedIPs) != "" {
		w1(envSetting("GYDS_ALLOWED_IPS", cfg.AllowedIPs))
	} else {
		w1("# GYDS_ALLOWED_IPS=")
	}
	w1("")
	w1("# ── Logging ────────────────────────────────────────────────────")
	w1(envSetting("GYDS_LOG_LEVEL", cfg.LogLevel))
	w1(envSetting("GYDS_LOG_FORMAT", cfg.LogFormat))

	content := sb.String()

	if err := os.WriteFile(".env", []byte(content), 0600); err != nil {
		jsonErr(w, http.StatusInternalServerError, "failed to write .env: "+err.Error())
		return
	}

	// If a dashboard PIN was provided during setup, set it in the directory
	// that the wizard is configuring. The running server may still be using a
	// previous data directory, so using s.auth here would make the PIN
	// disappear after the configured node restarts.
	pinMsg := ""
	if pin != "" {
		setupAuth := NewAuthStore(cfg.DataDir)
		if !setupAuth.PinIsSet() {
			if err := setupAuth.SetPin(pin); err != nil {
				// Non-fatal: .env was saved; report PIN error in response.
				pinMsg = "Warning: PIN not set — " + err.Error()
			} else {
				// Keep the running process aligned with the configuration so
				// the new PIN works before the operator restarts the node.
				s.auth = setupAuth
				pinMsg = "Dashboard PIN set successfully"
			}
		} else {
			pinMsg = "Dashboard PIN already set (skipped)"
		}
	}

	resp := map[string]interface{}{
		"ok":      true,
		"message": ".env saved successfully",
		"env":     content,
	}
	if pinMsg != "" {
		resp["pinStatus"] = pinMsg
	}
	jsonOK(w, resp)
}
