CREATE TABLE "user_stablecoins" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"creator_id" text NOT NULL,
	"name" text NOT NULL,
	"symbol" text NOT NULL,
	"decimals" integer DEFAULT 18 NOT NULL,
	"description" text,
	"logo_url" text,
	"peg_type" text DEFAULT 'usd' NOT NULL,
	"peg_value" numeric DEFAULT '1.00' NOT NULL,
	"basket_weights" jsonb DEFAULT '[]'::jsonb,
	"collateral_type" text DEFAULT 'over_collateralized' NOT NULL,
	"collateral_ratio" numeric DEFAULT '150' NOT NULL,
	"liquidation_threshold" numeric DEFAULT '120' NOT NULL,
	"reserve_assets" jsonb DEFAULT '["GYD","GYDS"]'::jsonb NOT NULL,
	"stability_fee" numeric DEFAULT '2.50' NOT NULL,
	"minting_fee" numeric DEFAULT '0.50' NOT NULL,
	"burn_fee" numeric DEFAULT '0.10' NOT NULL,
	"total_supply" numeric DEFAULT '0' NOT NULL,
	"circulating_supply" numeric DEFAULT '0' NOT NULL,
	"total_collateral_usd" numeric DEFAULT '0' NOT NULL,
	"website_url" text,
	"twitter_url" text,
	"address" text,
	"status" text DEFAULT 'pending_review' NOT NULL,
	"is_approved" boolean DEFAULT false NOT NULL,
	"approved_by" text,
	"approved_at" timestamp,
	"paused_reason" text,
	"creation_fee_paid" numeric DEFAULT '0' NOT NULL,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	CONSTRAINT "user_stablecoins_symbol_unique" UNIQUE("symbol")
);
