/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as openzeppelin from "./@openzeppelin";
export { UserStablecoin__factory } from "./UserStablecoin__factory";
