import { useState, useEffect } from 'react';
import { GlassCard } from '@/components/ui/GlassCard';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { useToast } from '@/hooks/use-toast';
import { useAuth } from '@/contexts/AuthContext';
import {
  Network, Download, Copy, RefreshCw, Loader2, CheckCircle,
  Shield, Server, Key, Wifi, WifiOff, ChevronDown, ChevronUp
} from 'lucide-react';

interface WgPeer {
  id: string;
  hostname: string;
  ip_address: string;
  wireguard_public_key: string | null;
  node_type: string;
  is_approved: boolean;
  is_synced: boolean;
  created_at: string;
  // assigned WireGuard tunnel IP
  wgIp?: string;
}

// WireGuard tunnel subnet: 10.8.0.0/24
// Server = 10.8.0.1 — peers get .2, .3, …
const assignWgIp = (index: number) => `10.8.0.${index + 2}`;

// Generate peer config block
const peerBlock = (peer: WgPeer, index: number): string => {
  if (!peer.wireguard_public_key) return `# Node ${peer.hostname} — no WireGuard key registered\n`;
  return [
    `# Peer: ${peer.hostname} (${peer.node_type})`,
    `[Peer]`,
    `PublicKey = ${peer.wireguard_public_key}`,
    `AllowedIPs = ${assignWgIp(index)}/32`,
    `PersistentKeepalive = 25`,
    ``,
  ].join('\n');
};

// Generate full server wg0.conf
const generateServerConfig = (peers: WgPeer[], serverPrivKey: string, serverPort: number): string => {
  const header = [
    '# WireGuard Server Config — GYDS Network',
    '# Generated by ChainCore Admin Panel',
    `# Generated: ${new Date().toISOString()}`,
    '',
    '[Interface]',
    `Address = 10.8.0.1/24`,
    `ListenPort = ${serverPort}`,
    `PrivateKey = ${serverPrivKey}`,
    'PostUp = iptables -A FORWARD -i wg0 -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE',
    'PostDown = iptables -D FORWARD -i wg0 -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE',
    '',
  ].join('\n');

  const peersSection = peers.map((p, i) => peerBlock(p, i)).join('\n');
  return header + peersSection;
};

// Generate per-peer client config
const generatePeerConfig = (peer: WgPeer, index: number, serverPubKey: string, serverEndpoint: string, serverPort: number): string => {
  return [
    `# WireGuard Client Config — ${peer.hostname}`,
    `# Generated by ChainCore Admin Panel`,
    `# Generated: ${new Date().toISOString()}`,
    '',
    '[Interface]',
    `Address = ${assignWgIp(index)}/24`,
    `PrivateKey = <REPLACE_WITH_THIS_NODE_PRIVATE_KEY>`,
    `DNS = 1.1.1.1, 8.8.8.8`,
    '',
    '[Peer]',
    `# GYDS Network Server`,
    `PublicKey = ${serverPubKey}`,
    `Endpoint = ${serverEndpoint}:${serverPort}`,
    `AllowedIPs = 10.8.0.0/24`,
    `PersistentKeepalive = 25`,
    '',
  ].join('\n');
};

const copyToClipboard = (text: string, label: string, toast: any) => {
  navigator.clipboard.writeText(text).then(() => toast({ title: `${label} copied!` }));
};

const downloadFile = (content: string, filename: string) => {
  const blob = new Blob([content], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url; a.download = filename; a.click();
  URL.revokeObjectURL(url);
};

export const WireGuardPeerManager = () => {
  const { user } = useAuth();
  const { toast } = useToast();
  const [peers, setPeers] = useState<WgPeer[]>([]);
  const [loading, setLoading] = useState(true);
  const [serverPrivKey, setServerPrivKey] = useState('');
  const [serverPubKey, setServerPubKey] = useState('');
  const [serverEndpoint, setServerEndpoint] = useState('');
  const [serverPort, setServerPort] = useState(51820);
  const [expandedPeer, setExpandedPeer] = useState<string | null>(null);

  useEffect(() => { loadPeers(); loadServerConfig(); }, []);

  const loadPeers = async () => {
    setLoading(true);
    try {
      const res = await fetch('/api/nodes?approved=true', { credentials: 'include' });
      if (res.ok) {
        const data: WgPeer[] = await res.json();
        setPeers(data.filter(n => n.is_approved));
      }
    } finally {
      setLoading(false);
    }
  };

  const loadServerConfig = async () => {
    try {
      const res = await fetch('/api/config/wireguard_server', { credentials: 'include' });
      if (res.ok) {
        const data = await res.json();
        setServerPrivKey(data.private_key ?? '');
        setServerPubKey(data.public_key ?? '');
        setServerEndpoint(data.endpoint ?? window.location.hostname);
        setServerPort(data.port ?? 51820);
      }
    } catch { /* not critical */ }
  };

  const saveServerConfig = async () => {
    await fetch('/api/config', {
      method: 'POST', credentials: 'include',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        key: 'wireguard_server',
        value: { private_key: serverPrivKey, public_key: serverPubKey, endpoint: serverEndpoint, port: serverPort },
      }),
    });
    toast({ title: '✅ WireGuard server config saved' });
  };

  const approvedPeers = peers.filter(p => p.is_approved);
  const peersWithKey = approvedPeers.filter(p => p.wireguard_public_key);

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h3 className="text-base font-semibold flex items-center gap-2">
            <Network className="h-5 w-5 text-primary" /> WireGuard Peer Manager
          </h3>
          <p className="text-xs text-muted-foreground mt-0.5">
            {approvedPeers.length} approved nodes · {peersWithKey.length} with WireGuard keys
          </p>
        </div>
        <Button variant="outline" size="sm" onClick={loadPeers} className="gap-1.5">
          <RefreshCw className="h-3.5 w-3.5" /> Refresh
        </Button>
      </div>

      {/* Server config */}
      <GlassCard className="p-4 space-y-3">
        <h4 className="text-sm font-medium flex items-center gap-2 mb-3">
          <Server className="h-4 w-4 text-primary" /> Server Configuration
        </h4>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
          <div className="space-y-1">
            <label className="text-xs text-muted-foreground">Server Public Key</label>
            <div className="flex gap-2">
              <input value={serverPubKey} onChange={e => setServerPubKey(e.target.value)}
                placeholder="Server WireGuard public key"
                className="flex-1 h-8 px-2 rounded bg-background border border-border text-xs font-mono focus:outline-none focus:border-primary" />
              <button onClick={() => copyToClipboard(serverPubKey, 'Public key', toast)} className="text-muted-foreground hover:text-foreground">
                <Copy className="h-3.5 w-3.5" />
              </button>
            </div>
          </div>
          <div className="space-y-1">
            <label className="text-xs text-muted-foreground">Server Private Key</label>
            <input value={serverPrivKey} onChange={e => setServerPrivKey(e.target.value)}
              placeholder="Server WireGuard private key (keep secret)"
              type="password"
              className="w-full h-8 px-2 rounded bg-background border border-border text-xs font-mono focus:outline-none focus:border-primary" />
          </div>
          <div className="space-y-1">
            <label className="text-xs text-muted-foreground">Server Endpoint (public IP/hostname)</label>
            <input value={serverEndpoint} onChange={e => setServerEndpoint(e.target.value)}
              placeholder="your-server.example.com"
              className="w-full h-8 px-2 rounded bg-background border border-border text-xs font-mono focus:outline-none focus:border-primary" />
          </div>
          <div className="space-y-1">
            <label className="text-xs text-muted-foreground">Listen Port</label>
            <input type="number" value={serverPort} onChange={e => setServerPort(Number(e.target.value))}
              className="w-full h-8 px-2 rounded bg-background border border-border text-xs font-mono focus:outline-none focus:border-primary" />
          </div>
        </div>
        <div className="flex gap-2 pt-1">
          <Button size="sm" onClick={saveServerConfig} className="gap-1.5 text-xs">
            <Shield className="h-3.5 w-3.5" /> Save Config
          </Button>
          <Button variant="outline" size="sm" onClick={() => downloadFile(generateServerConfig(approvedPeers, serverPrivKey, serverPort), 'wg0.conf')} className="gap-1.5 text-xs">
            <Download className="h-3.5 w-3.5" /> Download wg0.conf
          </Button>
          <Button variant="outline" size="sm" onClick={() => copyToClipboard(generateServerConfig(approvedPeers, serverPrivKey, serverPort), 'Server config', toast)} className="gap-1.5 text-xs">
            <Copy className="h-3.5 w-3.5" /> Copy Config
          </Button>
        </div>
      </GlassCard>

      {/* Peer list */}
      {loading ? (
        <div className="flex justify-center py-8"><Loader2 className="h-5 w-5 animate-spin text-muted-foreground" /></div>
      ) : approvedPeers.length === 0 ? (
        <GlassCard className="p-8 text-center text-muted-foreground">
          <WifiOff className="h-8 w-8 mx-auto mb-2 opacity-40" />
          <p className="text-sm">No approved nodes yet. Approve nodes in the Nodes tab first.</p>
        </GlassCard>
      ) : (
        <div className="space-y-2">
          {approvedPeers.map((peer, index) => {
            const tunnelIp = assignWgIp(index);
            const hasKey = !!peer.wireguard_public_key;
            const isExpanded = expandedPeer === peer.id;
            const peerCfg = generatePeerConfig(peer, index, serverPubKey, serverEndpoint, serverPort);

            return (
              <GlassCard key={peer.id} className="p-0 overflow-hidden">
                <button
                  className="w-full p-3 flex items-center justify-between text-left hover:bg-secondary/10 transition-colors"
                  onClick={() => setExpandedPeer(isExpanded ? null : peer.id)}
                >
                  <div className="flex items-center gap-3">
                    <div className={`w-2 h-2 rounded-full shrink-0 ${hasKey ? 'bg-green-400' : 'bg-yellow-400'}`} />
                    <div>
                      <p className="text-sm font-medium">{peer.hostname || peer.ip_address}</p>
                      <p className="text-xs text-muted-foreground font-mono">{peer.ip_address} → tunnel {tunnelIp}</p>
                    </div>
                  </div>
                  <div className="flex items-center gap-2">
                    <Badge variant="outline" className="text-xs capitalize">{peer.node_type}</Badge>
                    {hasKey
                      ? <Badge variant="outline" className="text-xs text-green-400 border-green-400"><Wifi className="h-2.5 w-2.5 mr-1" />Ready</Badge>
                      : <Badge variant="outline" className="text-xs text-yellow-400 border-yellow-400"><Key className="h-2.5 w-2.5 mr-1" />No Key</Badge>
                    }
                    {isExpanded ? <ChevronUp className="h-4 w-4 text-muted-foreground" /> : <ChevronDown className="h-4 w-4 text-muted-foreground" />}
                  </div>
                </button>

                {isExpanded && (
                  <div className="border-t border-border/30 p-3 space-y-3 bg-secondary/10">
                    {hasKey && (
                      <>
                        <div className="space-y-1">
                          <p className="text-xs text-muted-foreground font-medium">WireGuard Public Key</p>
                          <div className="flex gap-2 items-center">
                            <code className="text-xs font-mono bg-background rounded p-1.5 flex-1 break-all border border-border/50">
                              {peer.wireguard_public_key}
                            </code>
                            <button onClick={() => copyToClipboard(peer.wireguard_public_key!, 'Public key', toast)}>
                              <Copy className="h-3.5 w-3.5 text-muted-foreground hover:text-foreground" />
                            </button>
                          </div>
                        </div>

                        <div className="space-y-1">
                          <p className="text-xs text-muted-foreground font-medium">Peer Config Block (for server wg0.conf)</p>
                          <div className="flex gap-2 items-start">
                            <pre className="text-xs font-mono bg-background rounded p-2 flex-1 border border-border/50 whitespace-pre-wrap">
                              {peerBlock(peer, index)}
                            </pre>
                            <button onClick={() => copyToClipboard(peerBlock(peer, index), 'Peer block', toast)}>
                              <Copy className="h-3.5 w-3.5 text-muted-foreground hover:text-foreground mt-1" />
                            </button>
                          </div>
                        </div>
                      </>
                    )}

                    {!hasKey && (
                      <div className="text-xs text-yellow-400 flex items-center gap-2">
                        <Key className="h-3.5 w-3.5 shrink-0" />
                        This node has not registered a WireGuard public key. Ask the node operator to update their registration.
                      </div>
                    )}

                    <div className="flex gap-2">
                      <Button variant="outline" size="sm" className="gap-1.5 text-xs flex-1"
                        onClick={() => downloadFile(peerCfg, `wg-${peer.hostname || peer.ip_address}.conf`)}>
                        <Download className="h-3 w-3" /> Download Client Config
                      </Button>
                      <Button variant="outline" size="sm" className="gap-1.5 text-xs"
                        onClick={() => copyToClipboard(peerCfg, 'Client config', toast)}>
                        <Copy className="h-3 w-3" /> Copy
                      </Button>
                    </div>
                  </div>
                )}
              </GlassCard>
            );
          })}
        </div>
      )}

      {/* Summary */}
      {approvedPeers.length > 0 && (
        <GlassCard className="p-3 flex items-center justify-between">
          <div className="flex items-center gap-4 text-xs">
            <span className="text-muted-foreground">Total peers: <strong className="text-foreground">{approvedPeers.length}</strong></span>
            <span className="text-muted-foreground">With keys: <strong className="text-green-400">{peersWithKey.length}</strong></span>
            <span className="text-muted-foreground">Subnet: <strong className="text-foreground font-mono">10.8.0.0/24</strong></span>
          </div>
          <Button variant="outline" size="sm" className="gap-1.5 text-xs"
            onClick={() => {
              const allPeerBlocks = approvedPeers.map((p, i) => peerBlock(p, i)).join('\n');
              copyToClipboard(allPeerBlocks, 'All peer blocks', toast);
            }}>
            <Copy className="h-3 w-3" /> Copy All Peer Blocks
          </Button>
        </GlassCard>
      )}
    </div>
  );
};
