"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.passwordResetTokens = exports.userAchievements = exports.achievements = exports.xpEvents = exports.userXp = exports.communityVotes = exports.communityComments = exports.communityPosts = exports.governanceVotes = exports.governanceProposals = exports.vaultPositions = exports.orders = exports.faucetClaims = exports.auditLogs = exports.ddosProtection = exports.rateLimitRules = exports.ipAccessList = exports.fail2banJails = exports.firewallRules = exports.validatorDelegations = exports.networkValidators = exports.tokenPriceAlerts = exports.tokenWatchlist = exports.liquidityPools = exports.tokenLaunches = exports.tokens = exports.tokenPrice = exports.tokenOperations = exports.adminConfig = exports.documentation = exports.transactions = exports.nodeInstallations = exports.wallets = exports.profiles = exports.userRoles = exports.users = exports.appRoleEnum = void 0;
const pg_core_1 = require("drizzle-orm/pg-core");
const drizzle_orm_1 = require("drizzle-orm");
exports.appRoleEnum = (0, pg_core_1.pgEnum)("app_role", ["user", "admin", "founder"]);
exports.users = (0, pg_core_1.pgTable)("users", {
    id: (0, pg_core_1.text)("id").primaryKey(),
    email: (0, pg_core_1.text)("email"),
    username: (0, pg_core_1.text)("username").unique(),
    passwordHash: (0, pg_core_1.text)("password_hash"),
    walletAddress: (0, pg_core_1.text)("wallet_address").unique(),
    authNonce: (0, pg_core_1.text)("auth_nonce"),
    firstName: (0, pg_core_1.text)("first_name"),
    lastName: (0, pg_core_1.text)("last_name"),
    profileImageUrl: (0, pg_core_1.text)("profile_image_url"),
    totpSecret: (0, pg_core_1.text)("totp_secret"),
    totpEnabled: (0, pg_core_1.boolean)("totp_enabled").default(false),
    isBanned: (0, pg_core_1.boolean)("is_banned").default(false),
    createdAt: (0, pg_core_1.timestamp)("created_at").defaultNow(),
    updatedAt: (0, pg_core_1.timestamp)("updated_at").defaultNow(),
});
exports.userRoles = (0, pg_core_1.pgTable)("user_roles", {
    id: (0, pg_core_1.uuid)("id").primaryKey().default((0, drizzle_orm_1.sql) `gen_random_uuid()`),
    userId: (0, pg_core_1.text)("user_id").notNull().references(() => exports.users.id, { onDelete: "cascade" }),
    role: (0, exports.appRoleEnum)("role").notNull().default("user"),
});
exports.profiles = (0, pg_core_1.pgTable)("profiles", {
    id: (0, pg_core_1.uuid)("id").primaryKey().default((0, drizzle_orm_1.sql) `gen_random_uuid()`),
    userId: (0, pg_core_1.text)("user_id").notNull().unique().references(() => exports.users.id, { onDelete: "cascade" }),
    email: (0, pg_core_1.text)("email"),
    role: (0, pg_core_1.text)("role").notNull().default("user"),
    displayName: (0, pg_core_1.text)("display_name"),
    username: (0, pg_core_1.text)("username"),
    bio: (0, pg_core_1.text)("bio"),
    avatarUrl: (0, pg_core_1.text)("avatar_url"),
    locale: (0, pg_core_1.text)("locale").default("en"),
    timezone: (0, pg_core_1.text)("timezone").default("UTC"),
    notificationPrefs: (0, pg_core_1.jsonb)("notification_prefs"),
    metadata: (0, pg_core_1.jsonb)("metadata"),
    createdAt: (0, pg_core_1.timestamp)("created_at").defaultNow(),
    updatedAt: (0, pg_core_1.timestamp)("updated_at").defaultNow(),
});
exports.wallets = (0, pg_core_1.pgTable)("wallets", {
    id: (0, pg_core_1.uuid)("id").primaryKey().default((0, drizzle_orm_1.sql) `gen_random_uuid()`),
    userId: (0, pg_core_1.text)("user_id").notNull().references(() => exports.users.id, { onDelete: "cascade" }),
    address: (0, pg_core_1.text)("address").notNull(),
    encryptedSeed: (0, pg_core_1.text)("encrypted_seed").notNull().default(""),
    pinHash: (0, pg_core_1.text)("pin_hash").notNull().default(""),
    createdAt: (0, pg_core_1.timestamp)("created_at").defaultNow(),
});
exports.nodeInstallations = (0, pg_core_1.pgTable)("node_installations", {
    id: (0, pg_core_1.uuid)("id").primaryKey().default((0, drizzle_orm_1.sql) `gen_random_uuid()`),
    userId: (0, pg_core_1.text)("user_id").notNull().references(() => exports.users.id, { onDelete: "cascade" }),
    nodeType: (0, pg_core_1.text)("node_type").notNull(),
    wireguardPublicKey: (0, pg_core_1.text)("wireguard_public_key"),
    wireguardPrivateKey: (0, pg_core_1.text)("wireguard_private_key"),
    isSynced: (0, pg_core_1.boolean)("is_synced").default(false),
    lastSyncAt: (0, pg_core_1.timestamp)("last_sync_at"),
    isApproved: (0, pg_core_1.boolean)("is_approved").default(false),
    approvedBy: (0, pg_core_1.text)("approved_by"),
    approvedAt: (0, pg_core_1.timestamp)("approved_at"),
    isOnline: (0, pg_core_1.boolean)("is_online").default(false),
    lastHeartbeat: (0, pg_core_1.timestamp)("last_heartbeat"),
    hashRate: (0, pg_core_1.bigint)("hash_rate", { mode: "number" }).default(0),
    validShares: (0, pg_core_1.bigint)("valid_shares", { mode: "number" }).default(0),
    totalRewards: (0, pg_core_1.numeric)("total_rewards").default("0"),
    uptimeSeconds: (0, pg_core_1.bigint)("uptime_seconds", { mode: "number" }).default(0),
    connectionQuality: (0, pg_core_1.integer)("connection_quality").default(100),
    syncProgress: (0, pg_core_1.integer)("sync_progress").default(0),
    blocksSynced: (0, pg_core_1.bigint)("blocks_synced", { mode: "number" }).default(0),
    lastBlockHeight: (0, pg_core_1.bigint)("last_block_height", { mode: "number" }).default(0),
    errorCount: (0, pg_core_1.integer)("error_count").default(0),
    peerCount: (0, pg_core_1.integer)("peer_count").default(0),
    createdAt: (0, pg_core_1.timestamp)("created_at").defaultNow(),
});
exports.transactions = (0, pg_core_1.pgTable)("transactions", {
    id: (0, pg_core_1.uuid)("id").primaryKey().default((0, drizzle_orm_1.sql) `gen_random_uuid()`),
    fromAddress: (0, pg_core_1.text)("from_address").notNull(),
    toAddress: (0, pg_core_1.text)("to_address").notNull(),
    amount: (0, pg_core_1.numeric)("amount").notNull(),
    fee: (0, pg_core_1.numeric)("fee").notNull().default("0.001"),
    txHash: (0, pg_core_1.text)("tx_hash").unique(),
    status: (0, pg_core_1.text)("status").notNull().default("pending"),
    blockHeight: (0, pg_core_1.bigint)("block_height", { mode: "number" }),
    walletId: (0, pg_core_1.uuid)("wallet_id"),
    userId: (0, pg_core_1.text)("user_id").notNull().references(() => exports.users.id, { onDelete: "cascade" }),
    createdAt: (0, pg_core_1.timestamp)("created_at").defaultNow(),
    confirmedAt: (0, pg_core_1.timestamp)("confirmed_at"),
});
exports.documentation = (0, pg_core_1.pgTable)("documentation", {
    id: (0, pg_core_1.uuid)("id").primaryKey().default((0, drizzle_orm_1.sql) `gen_random_uuid()`),
    slug: (0, pg_core_1.text)("slug").notNull().unique(),
    title: (0, pg_core_1.text)("title").notNull(),
    content: (0, pg_core_1.text)("content").notNull(),
    updatedBy: (0, pg_core_1.text)("updated_by"),
    createdAt: (0, pg_core_1.timestamp)("created_at").defaultNow(),
    updatedAt: (0, pg_core_1.timestamp)("updated_at").defaultNow(),
});
exports.adminConfig = (0, pg_core_1.pgTable)("admin_config", {
    id: (0, pg_core_1.uuid)("id").primaryKey().default((0, drizzle_orm_1.sql) `gen_random_uuid()`),
    configKey: (0, pg_core_1.text)("config_key").unique().notNull(),
    configValue: (0, pg_core_1.jsonb)("config_value").notNull(),
    updatedBy: (0, pg_core_1.text)("updated_by"),
    updatedAt: (0, pg_core_1.timestamp)("updated_at").defaultNow(),
});
exports.tokenOperations = (0, pg_core_1.pgTable)("token_operations", {
    id: (0, pg_core_1.uuid)("id").primaryKey().default((0, drizzle_orm_1.sql) `gen_random_uuid()`),
    operationType: (0, pg_core_1.text)("operation_type").notNull(),
    amount: (0, pg_core_1.numeric)("amount").notNull(),
    usdtAmount: (0, pg_core_1.numeric)("usdt_amount").default("0"),
    walletAddress: (0, pg_core_1.text)("wallet_address").notNull(),
    txHash: (0, pg_core_1.text)("tx_hash"),
    createdBy: (0, pg_core_1.text)("created_by"),
    createdAt: (0, pg_core_1.timestamp)("created_at").defaultNow(),
    status: (0, pg_core_1.text)("status").notNull().default("pending"),
});
exports.tokenPrice = (0, pg_core_1.pgTable)("token_price", {
    id: (0, pg_core_1.uuid)("id").primaryKey().default((0, drizzle_orm_1.sql) `gen_random_uuid()`),
    price: (0, pg_core_1.numeric)("price").notNull().default("0.0000001"),
    totalSupply: (0, pg_core_1.numeric)("total_supply").notNull().default("100000000000"),
    circulatingSupply: (0, pg_core_1.numeric)("circulating_supply").notNull().default("0"),
    burnedTotal: (0, pg_core_1.numeric)("burned_total").notNull().default("0"),
    updatedAt: (0, pg_core_1.timestamp)("updated_at").defaultNow(),
});
exports.tokens = (0, pg_core_1.pgTable)("tokens", {
    id: (0, pg_core_1.uuid)("id").primaryKey().default((0, drizzle_orm_1.sql) `gen_random_uuid()`),
    creatorId: (0, pg_core_1.text)("creator_id").notNull(),
    name: (0, pg_core_1.text)("name").notNull(),
    symbol: (0, pg_core_1.text)("symbol").notNull(),
    decimals: (0, pg_core_1.integer)("decimals").notNull().default(18),
    totalSupply: (0, pg_core_1.numeric)("total_supply").notNull(),
    burnedSupply: (0, pg_core_1.numeric)("burned_supply").notNull().default("0"),
    gydsLiquidity: (0, pg_core_1.numeric)("gyds_liquidity").notNull().default("0"),
    logoUrl: (0, pg_core_1.text)("logo_url"),
    lpLockType: (0, pg_core_1.text)("lp_lock_type").notNull().default("burned"),
    lpUnlockTime: (0, pg_core_1.timestamp)("lp_unlock_time"),
    freezeEnabled: (0, pg_core_1.boolean)("freeze_enabled").notNull().default(false),
    freezeHolder: (0, pg_core_1.text)("freeze_holder"),
    freezeLocked: (0, pg_core_1.boolean)("freeze_locked").notNull().default(false),
    updateEnabled: (0, pg_core_1.boolean)("update_enabled").notNull().default(false),
    updateHolder: (0, pg_core_1.text)("update_holder"),
    updateLocked: (0, pg_core_1.boolean)("update_locked").notNull().default(false),
    mintEnabled: (0, pg_core_1.boolean)("mint_enabled").notNull().default(false),
    mintHolder: (0, pg_core_1.text)("mint_holder"),
    mintLocked: (0, pg_core_1.boolean)("mint_locked").notNull().default(false),
    address: (0, pg_core_1.text)("address").notNull(),
    isActive: (0, pg_core_1.boolean)("is_active").notNull().default(true),
    networkType: (0, pg_core_1.text)("network_type").notNull().default("devnet"),
    mainnetPromotedAt: (0, pg_core_1.timestamp)("mainnet_promoted_at"),
    marketCapUsd: (0, pg_core_1.numeric)("market_cap_usd").notNull().default("0"),
    extraAuthorities: (0, pg_core_1.jsonb)("extra_authorities").notNull().default((0, drizzle_orm_1.sql) `'{}'::jsonb`),
    createdAt: (0, pg_core_1.timestamp)("created_at").defaultNow(),
    updatedAt: (0, pg_core_1.timestamp)("updated_at").defaultNow(),
});
exports.tokenLaunches = (0, pg_core_1.pgTable)("token_launches", {
    id: (0, pg_core_1.uuid)("id").primaryKey().default((0, drizzle_orm_1.sql) `gen_random_uuid()`),
    creatorId: (0, pg_core_1.text)("creator_id").notNull(),
    tokenId: (0, pg_core_1.uuid)("token_id"),
    name: (0, pg_core_1.text)("name").notNull(),
    symbol: (0, pg_core_1.text)("symbol").notNull(),
    description: (0, pg_core_1.text)("description"),
    logoUrl: (0, pg_core_1.text)("logo_url"),
    status: (0, pg_core_1.text)("status").notNull().default("pending"),
    targetRaise: (0, pg_core_1.numeric)("target_raise").notNull().default("0"),
    raisedAmount: (0, pg_core_1.numeric)("raised_amount").notNull().default("0"),
    participants: (0, pg_core_1.integer)("participants").notNull().default(0),
    bondingCurveType: (0, pg_core_1.text)("bonding_curve_type").notNull().default("linear"),
    bondingCurveSteepness: (0, pg_core_1.numeric)("bonding_curve_steepness").notNull().default("1.0"),
    initialPrice: (0, pg_core_1.numeric)("initial_price").notNull().default("0.001"),
    maxPrice: (0, pg_core_1.numeric)("max_price"),
    isPremier: (0, pg_core_1.boolean)("is_premier").notNull().default(false),
    startsAt: (0, pg_core_1.timestamp)("starts_at"),
    endsAt: (0, pg_core_1.timestamp)("ends_at"),
    createdAt: (0, pg_core_1.timestamp)("created_at").defaultNow(),
    updatedAt: (0, pg_core_1.timestamp)("updated_at").defaultNow(),
});
exports.liquidityPools = (0, pg_core_1.pgTable)("liquidity_pools", {
    id: (0, pg_core_1.uuid)("id").primaryKey().default((0, drizzle_orm_1.sql) `gen_random_uuid()`),
    creatorId: (0, pg_core_1.text)("creator_id").notNull(),
    tokenASymbol: (0, pg_core_1.text)("token_a_symbol").notNull(),
    tokenBSymbol: (0, pg_core_1.text)("token_b_symbol").notNull(),
    tokenAAddress: (0, pg_core_1.text)("token_a_address"),
    tokenBAddress: (0, pg_core_1.text)("token_b_address"),
    feeTier: (0, pg_core_1.numeric)("fee_tier").notNull().default("0.3"),
    tvl: (0, pg_core_1.numeric)("tvl").notNull().default("0"),
    volume24h: (0, pg_core_1.numeric)("volume_24h").notNull().default("0"),
    fees24h: (0, pg_core_1.numeric)("fees_24h").notNull().default("0"),
    apr: (0, pg_core_1.numeric)("apr").notNull().default("0"),
    isActive: (0, pg_core_1.boolean)("is_active").notNull().default(true),
    createdAt: (0, pg_core_1.timestamp)("created_at").defaultNow(),
    updatedAt: (0, pg_core_1.timestamp)("updated_at").defaultNow(),
});
exports.tokenWatchlist = (0, pg_core_1.pgTable)("token_watchlist", {
    id: (0, pg_core_1.uuid)("id").primaryKey().default((0, drizzle_orm_1.sql) `gen_random_uuid()`),
    userId: (0, pg_core_1.text)("user_id").notNull().references(() => exports.users.id, { onDelete: "cascade" }),
    tokenId: (0, pg_core_1.uuid)("token_id").notNull().references(() => exports.tokens.id, { onDelete: "cascade" }),
    createdAt: (0, pg_core_1.timestamp)("created_at").defaultNow(),
});
exports.tokenPriceAlerts = (0, pg_core_1.pgTable)("token_price_alerts", {
    id: (0, pg_core_1.uuid)("id").primaryKey().default((0, drizzle_orm_1.sql) `gen_random_uuid()`),
    userId: (0, pg_core_1.text)("user_id").notNull().references(() => exports.users.id, { onDelete: "cascade" }),
    tokenId: (0, pg_core_1.uuid)("token_id").notNull().references(() => exports.tokens.id, { onDelete: "cascade" }),
    targetPrice: (0, pg_core_1.numeric)("target_price").notNull(),
    direction: (0, pg_core_1.text)("direction").notNull().default("above"),
    isTriggered: (0, pg_core_1.boolean)("is_triggered").notNull().default(false),
    triggeredAt: (0, pg_core_1.timestamp)("triggered_at"),
    createdAt: (0, pg_core_1.timestamp)("created_at").defaultNow(),
});
exports.networkValidators = (0, pg_core_1.pgTable)("network_validators", {
    id: (0, pg_core_1.uuid)("id").primaryKey().default((0, drizzle_orm_1.sql) `gen_random_uuid()`),
    address: (0, pg_core_1.text)("address").notNull().unique(),
    name: (0, pg_core_1.text)("name"),
    stake: (0, pg_core_1.numeric)("stake").notNull().default("0"),
    commission: (0, pg_core_1.integer)("commission").notNull().default(10),
    isActive: (0, pg_core_1.boolean)("is_active").notNull().default(true),
    isJailed: (0, pg_core_1.boolean)("is_jailed").notNull().default(false),
    uptime: (0, pg_core_1.numeric)("uptime").notNull().default("100.00"),
    blocksProposed: (0, pg_core_1.bigint)("blocks_proposed", { mode: "number" }).notNull().default(0),
    lastVoteHeight: (0, pg_core_1.bigint)("last_vote_height", { mode: "number" }).notNull().default(0),
    createdAt: (0, pg_core_1.timestamp)("created_at").defaultNow(),
    updatedAt: (0, pg_core_1.timestamp)("updated_at").defaultNow(),
    createdBy: (0, pg_core_1.text)("created_by"),
});
exports.validatorDelegations = (0, pg_core_1.pgTable)("validator_delegations", {
    id: (0, pg_core_1.uuid)("id").primaryKey().default((0, drizzle_orm_1.sql) `gen_random_uuid()`),
    userId: (0, pg_core_1.text)("user_id").notNull(),
    validatorId: (0, pg_core_1.uuid)("validator_id").notNull().references(() => exports.networkValidators.id, { onDelete: "cascade" }),
    amount: (0, pg_core_1.numeric)("amount").notNull().default("0"),
    status: (0, pg_core_1.text)("status").notNull().default("active"),
    delegatedAt: (0, pg_core_1.timestamp)("delegated_at").defaultNow(),
    undelegatedAt: (0, pg_core_1.timestamp)("undelegated_at"),
    createdAt: (0, pg_core_1.timestamp)("created_at").defaultNow(),
});
exports.firewallRules = (0, pg_core_1.pgTable)("firewall_rules", {
    id: (0, pg_core_1.uuid)("id").primaryKey().default((0, drizzle_orm_1.sql) `gen_random_uuid()`),
    ruleType: (0, pg_core_1.text)("rule_type").notNull().default("ufw"),
    action: (0, pg_core_1.text)("action").notNull().default("allow"),
    protocol: (0, pg_core_1.text)("protocol").notNull().default("tcp"),
    port: (0, pg_core_1.text)("port"),
    ipAddress: (0, pg_core_1.text)("ip_address"),
    direction: (0, pg_core_1.text)("direction").notNull().default("in"),
    description: (0, pg_core_1.text)("description"),
    isActive: (0, pg_core_1.boolean)("is_active").notNull().default(true),
    createdBy: (0, pg_core_1.text)("created_by"),
    createdAt: (0, pg_core_1.timestamp)("created_at").defaultNow(),
    updatedAt: (0, pg_core_1.timestamp)("updated_at").defaultNow(),
});
exports.fail2banJails = (0, pg_core_1.pgTable)("fail2ban_jails", {
    id: (0, pg_core_1.uuid)("id").primaryKey().default((0, drizzle_orm_1.sql) `gen_random_uuid()`),
    jailName: (0, pg_core_1.text)("jail_name").notNull(),
    isEnabled: (0, pg_core_1.boolean)("is_enabled").notNull().default(true),
    maxRetries: (0, pg_core_1.integer)("max_retries").notNull().default(5),
    banTime: (0, pg_core_1.integer)("ban_time").notNull().default(3600),
    findTime: (0, pg_core_1.integer)("find_time").notNull().default(600),
    logPath: (0, pg_core_1.text)("log_path"),
    filterName: (0, pg_core_1.text)("filter_name"),
    action: (0, pg_core_1.text)("action").default("iptables-multiport"),
    description: (0, pg_core_1.text)("description"),
    bannedIps: (0, pg_core_1.text)("banned_ips").array().default((0, drizzle_orm_1.sql) `'{}'`),
    createdBy: (0, pg_core_1.text)("created_by"),
    createdAt: (0, pg_core_1.timestamp)("created_at").defaultNow(),
    updatedAt: (0, pg_core_1.timestamp)("updated_at").defaultNow(),
});
exports.ipAccessList = (0, pg_core_1.pgTable)("ip_access_list", {
    id: (0, pg_core_1.uuid)("id").primaryKey().default((0, drizzle_orm_1.sql) `gen_random_uuid()`),
    ipAddress: (0, pg_core_1.text)("ip_address").notNull(),
    listType: (0, pg_core_1.text)("list_type").notNull().default("whitelist"),
    reason: (0, pg_core_1.text)("reason"),
    expiresAt: (0, pg_core_1.timestamp)("expires_at"),
    createdBy: (0, pg_core_1.text)("created_by"),
    createdAt: (0, pg_core_1.timestamp)("created_at").defaultNow(),
});
exports.rateLimitRules = (0, pg_core_1.pgTable)("rate_limit_rules", {
    id: (0, pg_core_1.uuid)("id").primaryKey().default((0, drizzle_orm_1.sql) `gen_random_uuid()`),
    name: (0, pg_core_1.text)("name").notNull(),
    endpoint: (0, pg_core_1.text)("endpoint").notNull(),
    requestsPerWindow: (0, pg_core_1.integer)("requests_per_window").notNull().default(100),
    windowSeconds: (0, pg_core_1.integer)("window_seconds").notNull().default(60),
    burstLimit: (0, pg_core_1.integer)("burst_limit").notNull().default(20),
    action: (0, pg_core_1.text)("action").notNull().default("throttle"),
    isEnabled: (0, pg_core_1.boolean)("is_enabled").notNull().default(true),
    description: (0, pg_core_1.text)("description"),
    createdBy: (0, pg_core_1.text)("created_by"),
    createdAt: (0, pg_core_1.timestamp)("created_at").defaultNow(),
    updatedAt: (0, pg_core_1.timestamp)("updated_at").defaultNow(),
});
exports.ddosProtection = (0, pg_core_1.pgTable)("ddos_protection", {
    id: (0, pg_core_1.uuid)("id").primaryKey().default((0, drizzle_orm_1.sql) `gen_random_uuid()`),
    name: (0, pg_core_1.text)("name").notNull(),
    protectionType: (0, pg_core_1.text)("protection_type").notNull().default("syn_flood"),
    threshold: (0, pg_core_1.integer)("threshold").notNull().default(1000),
    action: (0, pg_core_1.text)("action").notNull().default("drop"),
    isEnabled: (0, pg_core_1.boolean)("is_enabled").notNull().default(true),
    parameters: (0, pg_core_1.jsonb)("parameters").default((0, drizzle_orm_1.sql) `'{}'::jsonb`),
    description: (0, pg_core_1.text)("description"),
    createdBy: (0, pg_core_1.text)("created_by"),
    createdAt: (0, pg_core_1.timestamp)("created_at").defaultNow(),
    updatedAt: (0, pg_core_1.timestamp)("updated_at").defaultNow(),
});
exports.auditLogs = (0, pg_core_1.pgTable)("audit_logs", {
    id: (0, pg_core_1.uuid)("id").primaryKey().default((0, drizzle_orm_1.sql) `gen_random_uuid()`),
    userId: (0, pg_core_1.text)("user_id").notNull(),
    userEmail: (0, pg_core_1.text)("user_email"),
    action: (0, pg_core_1.text)("action").notNull(),
    category: (0, pg_core_1.text)("category").notNull().default("general"),
    targetType: (0, pg_core_1.text)("target_type"),
    targetId: (0, pg_core_1.text)("target_id"),
    details: (0, pg_core_1.jsonb)("details").default((0, drizzle_orm_1.sql) `'{}'::jsonb`),
    ipAddress: (0, pg_core_1.text)("ip_address"),
    createdAt: (0, pg_core_1.timestamp)("created_at").defaultNow(),
});
exports.faucetClaims = (0, pg_core_1.pgTable)("faucet_claims", {
    id: (0, pg_core_1.uuid)("id").primaryKey().default((0, drizzle_orm_1.sql) `gen_random_uuid()`),
    userId: (0, pg_core_1.text)("user_id").notNull(),
    walletAddress: (0, pg_core_1.text)("wallet_address").notNull(),
    tokenType: (0, pg_core_1.text)("token_type").notNull(),
    amount: (0, pg_core_1.numeric)("amount").notNull(),
    txHash: (0, pg_core_1.text)("tx_hash"),
    ipAddress: (0, pg_core_1.text)("ip_address"),
    createdAt: (0, pg_core_1.timestamp)("created_at").defaultNow(),
});
exports.orders = (0, pg_core_1.pgTable)("orders", {
    id: (0, pg_core_1.uuid)("id").primaryKey().default((0, drizzle_orm_1.sql) `gen_random_uuid()`),
    userId: (0, pg_core_1.text)("user_id").notNull().references(() => exports.users.id, { onDelete: "cascade" }),
    side: (0, pg_core_1.text)("side").notNull(),
    orderType: (0, pg_core_1.text)("order_type").notNull(),
    price: (0, pg_core_1.numeric)("price"),
    stopPrice: (0, pg_core_1.numeric)("stop_price"),
    amount: (0, pg_core_1.numeric)("amount").notNull(),
    filled: (0, pg_core_1.numeric)("filled").notNull().default("0"),
    status: (0, pg_core_1.text)("status").notNull().default("open"),
    createdAt: (0, pg_core_1.timestamp)("created_at").defaultNow(),
    updatedAt: (0, pg_core_1.timestamp)("updated_at").defaultNow(),
});
exports.vaultPositions = (0, pg_core_1.pgTable)("vault_positions", {
    id: (0, pg_core_1.uuid)("id").primaryKey().default((0, drizzle_orm_1.sql) `gen_random_uuid()`),
    userId: (0, pg_core_1.text)("user_id").notNull().references(() => exports.users.id, { onDelete: "cascade" }),
    vaultId: (0, pg_core_1.text)("vault_id").notNull(),
    vaultName: (0, pg_core_1.text)("vault_name").notNull(),
    token: (0, pg_core_1.text)("token").notNull(),
    amount: (0, pg_core_1.numeric)("amount").notNull(),
    apy: (0, pg_core_1.numeric)("apy").notNull(),
    autoCompound: (0, pg_core_1.boolean)("auto_compound").notNull().default(true),
    lockDays: (0, pg_core_1.integer)("lock_days"),
    lockedUntil: (0, pg_core_1.timestamp)("locked_until"),
    status: (0, pg_core_1.text)("status").notNull().default("active"),
    depositedAt: (0, pg_core_1.timestamp)("deposited_at").defaultNow(),
    withdrawnAt: (0, pg_core_1.timestamp)("withdrawn_at"),
});
exports.governanceProposals = (0, pg_core_1.pgTable)("governance_proposals", {
    id: (0, pg_core_1.uuid)("id").primaryKey().default((0, drizzle_orm_1.sql) `gen_random_uuid()`),
    title: (0, pg_core_1.text)("title").notNull(),
    description: (0, pg_core_1.text)("description").notNull(),
    proposalType: (0, pg_core_1.text)("proposal_type").notNull().default("parameter"),
    status: (0, pg_core_1.text)("status").notNull().default("active"),
    votesFor: (0, pg_core_1.numeric)("votes_for").notNull().default("0"),
    votesAgainst: (0, pg_core_1.numeric)("votes_against").notNull().default("0"),
    votesAbstain: (0, pg_core_1.numeric)("votes_abstain").notNull().default("0"),
    quorumRequired: (0, pg_core_1.numeric)("quorum_required").notNull().default("1000000"),
    createdBy: (0, pg_core_1.text)("created_by").notNull().references(() => exports.users.id),
    endDate: (0, pg_core_1.timestamp)("end_date").notNull(),
    createdAt: (0, pg_core_1.timestamp)("created_at").defaultNow(),
});
exports.governanceVotes = (0, pg_core_1.pgTable)("governance_votes", {
    id: (0, pg_core_1.uuid)("id").primaryKey().default((0, drizzle_orm_1.sql) `gen_random_uuid()`),
    proposalId: (0, pg_core_1.uuid)("proposal_id").notNull().references(() => exports.governanceProposals.id, { onDelete: "cascade" }),
    userId: (0, pg_core_1.text)("user_id").notNull().references(() => exports.users.id),
    choice: (0, pg_core_1.text)("choice").notNull(),
    votingPower: (0, pg_core_1.numeric)("voting_power").notNull().default("1"),
    createdAt: (0, pg_core_1.timestamp)("created_at").defaultNow(),
});
exports.communityPosts = (0, pg_core_1.pgTable)("community_posts", {
    id: (0, pg_core_1.uuid)("id").primaryKey().default((0, drizzle_orm_1.sql) `gen_random_uuid()`),
    userId: (0, pg_core_1.text)("user_id").notNull().references(() => exports.users.id),
    title: (0, pg_core_1.text)("title").notNull(),
    body: (0, pg_core_1.text)("body").notNull(),
    postType: (0, pg_core_1.text)("post_type").notNull().default("discussion"),
    upvotes: (0, pg_core_1.integer)("upvotes").notNull().default(0),
    downvotes: (0, pg_core_1.integer)("downvotes").notNull().default(0),
    replyCount: (0, pg_core_1.integer)("reply_count").notNull().default(0),
    pinned: (0, pg_core_1.boolean)("pinned").notNull().default(false),
    createdAt: (0, pg_core_1.timestamp)("created_at").defaultNow(),
    updatedAt: (0, pg_core_1.timestamp)("updated_at").defaultNow(),
});
exports.communityComments = (0, pg_core_1.pgTable)("community_comments", {
    id: (0, pg_core_1.uuid)("id").primaryKey().default((0, drizzle_orm_1.sql) `gen_random_uuid()`),
    postId: (0, pg_core_1.uuid)("post_id").notNull().references(() => exports.communityPosts.id, { onDelete: "cascade" }),
    userId: (0, pg_core_1.text)("user_id").notNull().references(() => exports.users.id),
    body: (0, pg_core_1.text)("body").notNull(),
    upvotes: (0, pg_core_1.integer)("upvotes").notNull().default(0),
    createdAt: (0, pg_core_1.timestamp)("created_at").defaultNow(),
});
exports.communityVotes = (0, pg_core_1.pgTable)("community_votes", {
    id: (0, pg_core_1.uuid)("id").primaryKey().default((0, drizzle_orm_1.sql) `gen_random_uuid()`),
    userId: (0, pg_core_1.text)("user_id").notNull().references(() => exports.users.id),
    targetId: (0, pg_core_1.uuid)("target_id").notNull(),
    targetType: (0, pg_core_1.text)("target_type").notNull(),
    direction: (0, pg_core_1.text)("direction").notNull(),
    createdAt: (0, pg_core_1.timestamp)("created_at").defaultNow(),
});
exports.userXp = (0, pg_core_1.pgTable)("user_xp", {
    id: (0, pg_core_1.uuid)("id").primaryKey().default((0, drizzle_orm_1.sql) `gen_random_uuid()`),
    userId: (0, pg_core_1.text)("user_id").notNull().references(() => exports.users.id, { onDelete: "cascade" }).unique(),
    totalXp: (0, pg_core_1.integer)("total_xp").notNull().default(0),
    level: (0, pg_core_1.integer)("level").notNull().default(1),
    updatedAt: (0, pg_core_1.timestamp)("updated_at").defaultNow(),
});
exports.xpEvents = (0, pg_core_1.pgTable)("xp_events", {
    id: (0, pg_core_1.uuid)("id").primaryKey().default((0, drizzle_orm_1.sql) `gen_random_uuid()`),
    userId: (0, pg_core_1.text)("user_id").notNull().references(() => exports.users.id, { onDelete: "cascade" }),
    eventType: (0, pg_core_1.text)("event_type").notNull(),
    xpAwarded: (0, pg_core_1.integer)("xp_awarded").notNull(),
    description: (0, pg_core_1.text)("description"),
    createdAt: (0, pg_core_1.timestamp)("created_at").defaultNow(),
});
exports.achievements = (0, pg_core_1.pgTable)("achievements", {
    id: (0, pg_core_1.text)("id").primaryKey(),
    title: (0, pg_core_1.text)("title").notNull(),
    description: (0, pg_core_1.text)("description").notNull(),
    xpReward: (0, pg_core_1.integer)("xp_reward").notNull().default(0),
    icon: (0, pg_core_1.text)("icon").notNull().default("🏆"),
    category: (0, pg_core_1.text)("category").notNull().default("general"),
});
exports.userAchievements = (0, pg_core_1.pgTable)("user_achievements", {
    id: (0, pg_core_1.uuid)("id").primaryKey().default((0, drizzle_orm_1.sql) `gen_random_uuid()`),
    userId: (0, pg_core_1.text)("user_id").notNull().references(() => exports.users.id, { onDelete: "cascade" }),
    achievementId: (0, pg_core_1.text)("achievement_id").notNull().references(() => exports.achievements.id),
    unlockedAt: (0, pg_core_1.timestamp)("unlocked_at").defaultNow(),
});
exports.passwordResetTokens = (0, pg_core_1.pgTable)("password_reset_tokens", {
    id: (0, pg_core_1.uuid)("id").primaryKey().default((0, drizzle_orm_1.sql) `gen_random_uuid()`),
    userId: (0, pg_core_1.text)("user_id").notNull().references(() => exports.users.id, { onDelete: "cascade" }),
    token: (0, pg_core_1.text)("token").notNull().unique(),
    expiresAt: (0, pg_core_1.timestamp)("expires_at").notNull(),
    usedAt: (0, pg_core_1.timestamp)("used_at"),
    createdAt: (0, pg_core_1.timestamp)("created_at").defaultNow(),
});
