#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# GYDS Wallet — Auto-configure & clone script
# Run from the ChainCore project root:
#   bash mobile-wallet/configure.sh
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail

GREEN="\033[0;32m"; YELLOW="\033[1;33m"; CYAN="\033[0;36m"; NC="\033[0m"
log()  { echo -e "${GREEN}[wallet-setup]${NC} $*"; }
warn() { echo -e "${YELLOW}[warn]${NC} $*"; }
info() { echo -e "${CYAN}[info]${NC} $*"; }

WALLET_REPO="https://github.com/hc172808/your-digital-wallet.git"
WALLET_DIR="${1:-gyds-wallet}"

# ── 1. Check dependencies ─────────────────────────────────────────────────────
log "Checking dependencies..."
command -v git  >/dev/null || { warn "git not found — install it first"; exit 1; }
command -v node >/dev/null || { warn "node not found — install Node.js 20+"; exit 1; }
NODE_VER=$(node -e "process.stdout.write(process.version.slice(1).split('.')[0])")
if [[ "$NODE_VER" -lt 18 ]]; then warn "Node.js 18+ required (found v${NODE_VER})"; exit 1; fi

# ── 2. Get domain ─────────────────────────────────────────────────────────────
echo ""
read -r -p "  Your deployed domain (e.g. netlifegy.com): " DOMAIN
DOMAIN="${DOMAIN:-netlifegy.com}"
[[ "$DOMAIN" == http* ]] && DOMAIN="${DOMAIN#https://}" && DOMAIN="${DOMAIN#http://}"
DOMAIN="${DOMAIN%/}"

read -r -p "  ChainCore dashboard URL (default: https://${DOMAIN}): " DASHBOARD_URL
DASHBOARD_URL="${DASHBOARD_URL:-https://${DOMAIN}}"

# ── 3. Clone wallet repo ──────────────────────────────────────────────────────
if [[ -d "$WALLET_DIR/.git" ]]; then
  log "Wallet repo already cloned at ${WALLET_DIR} — pulling latest..."
  git -C "$WALLET_DIR" pull --ff-only
else
  log "Cloning wallet repo to ${WALLET_DIR}..."
  git clone "$WALLET_REPO" "$WALLET_DIR"
fi

# ── 4. Install dependencies ───────────────────────────────────────────────────
log "Installing wallet dependencies..."
if command -v bun >/dev/null; then
  (cd "$WALLET_DIR" && bun install --frozen-lockfile)
else
  warn "bun not found — using npm (bun is faster: https://bun.sh)"
  (cd "$WALLET_DIR" && npm ci)
fi

# ── 5. Write .env.local ───────────────────────────────────────────────────────
log "Writing ${WALLET_DIR}/.env.local..."
cat > "${WALLET_DIR}/.env.local" << EOF
# GYDS Wallet — auto-generated by configure.sh
# Edit as needed and re-run 'bun run build' to apply changes.

# ── Network ───────────────────────────────────────────────────────────────────
VITE_RPC_URL=https://rpc.netlifegy.com
VITE_RPC_FALLBACKS=https://rpc2.netlifegy.com,https://rpc3.netlifegy.com
VITE_CHAIN_ID=198282
VITE_CHAIN_ID_HEX=0x3068a
VITE_NATIVE_SYMBOL=GYDS
VITE_NETWORK_NAME=GYDS Network
VITE_BLOCK_EXPLORER=https://explorer.netlifegy.com

# ── Your deployed domain ──────────────────────────────────────────────────────
VITE_DOMAIN=${DOMAIN}
VITE_API_BASE=${DASHBOARD_URL}
VITE_DASHBOARD_URL=${DASHBOARD_URL}

# ── App identity ──────────────────────────────────────────────────────────────
VITE_APP_NAME=GYDS Wallet
VITE_APP_ID=io.netlifegy.gyds
EOF

# ── 6. Patch Bubblewrap TWA manifest with domain ──────────────────────────────
TWA_MANIFEST="${WALLET_DIR}/mobile/bubblewrap/twa-manifest.json"
if [[ -f "$TWA_MANIFEST" ]]; then
  log "Patching TWA manifest with domain: ${DOMAIN}..."
  node -e "
    const fs = require('fs');
    const m = JSON.parse(fs.readFileSync('${TWA_MANIFEST}', 'utf8'));
    m.host = '${DOMAIN}';
    m.iconUrl = 'https://${DOMAIN}/pwa-512x512.png';
    m.maskableIconUrl = 'https://${DOMAIN}/pwa-512x512.png';
    m.shortcuts = m.shortcuts.map(s => ({ ...s, iconUrl: 'https://${DOMAIN}/pwa-192x192.png' }));
    fs.writeFileSync('${TWA_MANIFEST}', JSON.stringify(m, null, 2));
    console.log('  TWA manifest updated.');
  "
fi

# ── 7. Patch PWABuilder manifest ──────────────────────────────────────────────
PWAB="${WALLET_DIR}/mobile/pwabuilder.json"
if [[ -f "$PWAB" ]]; then
  log "Patching PWABuilder config with domain: ${DOMAIN}..."
  node -e "
    const fs = require('fs');
    const m = JSON.parse(fs.readFileSync('${PWAB}', 'utf8'));
    m.startUrl = 'https://${DOMAIN}/';
    m.iconUrl = '/pwa-512x512.png';
    m.maskableIconUrl = '/pwa-512x512.png';
    fs.writeFileSync('${PWAB}', JSON.stringify(m, null, 2));
    console.log('  PWABuilder config updated.');
  "
fi

# ── 8. Build the web app ──────────────────────────────────────────────────────
echo ""
read -r -p "  Build the wallet now? (Y/n): " BUILD_NOW
case "${BUILD_NOW,,}" in
  n|no) info "Skipping build. Run 'bun run build' inside ${WALLET_DIR} when ready." ;;
  *)
    log "Building wallet..."
    if command -v bun >/dev/null; then
      (cd "$WALLET_DIR" && bun run build)
    else
      (cd "$WALLET_DIR" && npm run build)
    fi
    log "Build complete → ${WALLET_DIR}/dist/"
    ;;
esac

# ── 9. Summary ────────────────────────────────────────────────────────────────
echo ""
echo "╔══════════════════════════════════════════════════════════════╗"
echo "║         GYDS Wallet — Configured ✓                          ║"
echo "╠══════════════════════════════════════════════════════════════╣"
echo "║                                                              ║"
echo "║  Directory  : ${WALLET_DIR}"
echo "║  Domain     : ${DOMAIN}"
echo "║  Dashboard  : ${DASHBOARD_URL}"
echo "║  App ID     : io.netlifegy.gyds"
echo "║                                                              ║"
echo "╠══════════════════════════════════════════════════════════════╣"
echo "║  NEXT STEPS                                                  ║"
echo "╠══════════════════════════════════════════════════════════════╣"
echo "║                                                              ║"
echo "║  ① Capacitor (native Android/iOS):                          ║"
echo "║     cd ${WALLET_DIR}/mobile && npx cap add android           ║"
echo "║     npx cap copy && npx cap open android                     ║"
echo "║                                                              ║"
echo "║  ② Bubblewrap TWA (Android — smallest APK):                  ║"
echo "║     cd ${WALLET_DIR}/mobile/bubblewrap                       ║"
echo "║     bubblewrap build                                         ║"
echo "║                                                              ║"
echo "║  ③ PWABuilder (no toolchain needed):                         ║"
echo "║     Visit https://www.pwabuilder.com → enter ${DOMAIN}       ║"
echo "║                                                              ║"
echo "║  Full guide: mobile-wallet/SETUP.md                          ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""
