#!/usr/bin/env bash
#═══════════════════════════════════════════════════════════════════════════════
#  GYDSchain Dev Node Installer
#  Spins up a local devnet node (Chain ID 13372) for development and testing.
#  Clones source from https://github.com/hc172808/guardian-chain.git
#  Linux / macOS  |  No root required (user-mode)
#  Run:  bash install-devnode.sh
#═══════════════════════════════════════════════════════════════════════════════
set -euo pipefail

GYDS_VERSION="2.1.0"
CHAIN_ID="${CHAIN_ID:-13372}"
CHAIN_NAME="GYDS Devnet"
GO_VERSION="${GO_VERSION:-1.22.5}"

REPO_URL="${REPO_URL:-https://github.com/hc172808/guardian-chain.git}"

GYDS_HOME="${GYDS_HOME:-$HOME/.gydschain-devnet}"
GYDS_BIN="${GYDS_BIN:-$GYDS_HOME/bin}"

RPC_PORT="${RPC_PORT:-8548}"
P2P_PORT="${P2P_PORT:-30305}"
API_PORT="${API_PORT:-3032}"
WS_PORT="${WS_PORT:-8549}"

BLOCK_TIME="${BLOCK_TIME:-5}"
MINING_THREADS="${MINING_THREADS:-2}"
PREFUND_ADDRESSES="${PREFUND_ADDRESSES:-}"

GREEN='\033[0;32m'; YELLOW='\033[1;33m'; CYAN='\033[0;36m'; RED='\033[0;31m'; BOLD='\033[1m'; NC='\033[0m'
log()  { echo -e "${GREEN}[+]${NC} $*"; }
warn() { echo -e "${YELLOW}[!]${NC} $*"; }
err()  { echo -e "${RED}[✗]${NC} $*" >&2; }
step() { echo -e "\n${CYAN}${BOLD}──── $* ────${NC}"; }

echo -e "${CYAN}"
cat <<'EOF'
╔══════════════════════════════════════════════════════════════════╗
║   GYDSchain DEV NODE Installer                                   ║
║   Chain ID: 13372  |  GYDS Devnet  |  guardian-chain             ║
║   Fast blocks (5s) · Pre-funded accounts · Local-only            ║
╚══════════════════════════════════════════════════════════════════╝
EOF
echo -e "${NC}"

# ─── Detect OS ───────────────────────────────────────────────────────────────
OS="$(uname -s)"
ARCH="$(uname -m)"
[[ "$ARCH" == "x86_64" ]] && GOARCH="amd64"
[[ "$ARCH" == "aarch64" || "$ARCH" == "arm64" ]] && GOARCH="arm64"
[[ "$OS" == "Linux" ]] && GOOS="linux"
[[ "$OS" == "Darwin" ]] && GOOS="darwin"

# ─── 1. Dependencies ─────────────────────────────────────────────────────────
step "1/7  Installing dependencies"
if command -v apt-get >/dev/null 2>&1; then
  sudo apt-get update -qq
  sudo apt-get install -y -qq curl wget git build-essential jq openssl ca-certificates
elif command -v brew >/dev/null 2>&1; then
  brew install curl wget git jq openssl
elif command -v yum >/dev/null 2>&1; then
  sudo yum install -y -q curl wget git gcc jq openssl
else
  warn "Unknown package manager — ensure curl, git, jq, and build tools are installed."
fi

# ─── 2. Go ───────────────────────────────────────────────────────────────────
step "2/7  Ensuring Go ${GO_VERSION}"
if ! command -v go >/dev/null 2>&1 || [[ "$(go version | awk '{print $3}')" < "go1.22" ]]; then
  warn "Installing Go ${GO_VERSION}..."
  cd /tmp
  GO_TARBALL="go${GO_VERSION}.${GOOS}-${GOARCH}.tar.gz"
  wget -q "https://go.dev/dl/${GO_TARBALL}" -O go.tgz
  if [[ "$OS" == "Linux" ]]; then
    sudo rm -rf /usr/local/go && sudo tar -C /usr/local -xzf go.tgz && rm go.tgz
    sudo ln -sf /usr/local/go/bin/go    /usr/local/bin/go
    sudo ln -sf /usr/local/go/bin/gofmt /usr/local/bin/gofmt
  else
    # macOS — install to ~/sdk/go
    mkdir -p "$HOME/sdk"
    tar -C "$HOME/sdk" -xzf go.tgz && rm go.tgz
    export PATH="$HOME/sdk/go/bin:$PATH"
    echo 'export PATH="$HOME/sdk/go/bin:$PATH"' >> "$HOME/.profile"
  fi
fi
export PATH="$PATH:/usr/local/go/bin"
log "$(go version)"

# ─── 3. Clone source ─────────────────────────────────────────────────────────
step "3/7  Cloning guardian-chain source"
SRC_PARENT="$HOME/guardian-chain-src"
if [[ -d "$SRC_PARENT/.git" ]]; then
  log "Repo already cloned — pulling latest..."
  git -C "$SRC_PARENT" pull --ff-only
else
  git clone --depth=1 "$REPO_URL" "$SRC_PARENT"
fi

SRC_DIR="$SRC_PARENT/public/blockchain-go"
if [[ ! -d "$SRC_DIR/cmd/devnode" ]]; then
  warn "cmd/devnode not found — falling back to cmd/litenode"
  NODE_CMD="litenode"
  BIN_NAME="gyds-litenode"
else
  NODE_CMD="devnode"
  BIN_NAME="gyds-devnode"
fi

# ─── 4. Build binary ─────────────────────────────────────────────────────────
step "4/7  Building ${BIN_NAME}"
mkdir -p "$GYDS_BIN"
BUILD_DIR="$SRC_DIR/cmd/${NODE_CMD}"
cd "$BUILD_DIR"
GOOS="$GOOS" GOARCH="$GOARCH" go build \
  -ldflags "-s -w -X main.Version=${GYDS_VERSION} -X main.ChainID=${CHAIN_ID} -X main.BuildTime=$(date -u +%Y%m%dT%H%M%SZ)" \
  -o "$GYDS_BIN/$BIN_NAME" .
log "Built → $GYDS_BIN/$BIN_NAME"

# ─── 5. Create directories and config ────────────────────────────────────────
step "5/7  Writing devnet config"
mkdir -p "$GYDS_HOME"/{data,logs,keys,config}

# Genesis / devnet config
cat > "$GYDS_HOME/config/devnet.toml" <<TOML
# GYDSchain Devnet Configuration — Chain ID ${CHAIN_ID}
# Auto-generated by install-devnode.sh

[chain]
id        = ${CHAIN_ID}
name      = "${CHAIN_NAME}"
block_time = ${BLOCK_TIME}
network   = "devnet"

[node]
data_dir  = "${GYDS_HOME}/data"
log_dir   = "${GYDS_HOME}/logs"
key_dir   = "${GYDS_HOME}/keys"
log_level = "info"

[rpc]
enabled  = true
host     = "127.0.0.1"
port     = ${RPC_PORT}
ws_port  = ${WS_PORT}
cors     = ["*"]

[p2p]
port      = ${P2P_PORT}
max_peers = 8
bootnodes = []

[mining]
enabled = true
threads = ${MINING_THREADS}
algorithm = "randomx"

[api]
enabled = true
port    = ${API_PORT}

[devnet]
# Pre-funded developer accounts (1,000,000 GYDS each)
prefund = [
  "0x0000000000000000000000000000000000000001",
  "0x0000000000000000000000000000000000000002",
  ${PREFUND_ADDRESSES:+"\"$PREFUND_ADDRESSES\","}
]
instant_finality = true
TOML

# MetaMask / wallet network params
cat > "$GYDS_HOME/config/wallet-params.json" <<JSON
{
  "chainId": "0x343C",
  "chainName": "GYDS Devnet",
  "nativeCurrency": {
    "name": "Dev GYDS",
    "symbol": "dGYDS",
    "decimals": 18
  },
  "rpcUrls": ["http://127.0.0.1:${RPC_PORT}"],
  "blockExplorerUrls": ["https://devnet-explorer.netlifegy.com"]
}
JSON

log "Config written to $GYDS_HOME/config/"

# ─── 6. Systemd / launchd service ────────────────────────────────────────────
step "6/7  Installing service"

if [[ "$OS" == "Linux" ]] && command -v systemctl >/dev/null 2>&1; then
  SERVICE_FILE="/etc/systemd/system/gyds-devnode.service"
  sudo tee "$SERVICE_FILE" >/dev/null <<UNIT
[Unit]
Description=GYDSchain Dev Node (Chain ID ${CHAIN_ID})
After=network.target

[Service]
Type=simple
User=${USER}
ExecStart=${GYDS_BIN}/${BIN_NAME} \\
  --config ${GYDS_HOME}/config/devnet.toml \\
  --chain-id ${CHAIN_ID} \\
  --rpc-port ${RPC_PORT} \\
  --p2p-port ${P2P_PORT} \\
  --datadir ${GYDS_HOME}/data \\
  --log-dir ${GYDS_HOME}/logs
Restart=on-failure
RestartSec=10
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=multi-user.target
UNIT
  sudo systemctl daemon-reload
  sudo systemctl enable gyds-devnode
  log "systemd service installed: gyds-devnode.service"

elif [[ "$OS" == "Darwin" ]]; then
  PLIST="$HOME/Library/LaunchAgents/com.gydschain.devnode.plist"
  cat > "$PLIST" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key><string>com.gydschain.devnode</string>
  <key>ProgramArguments</key>
  <array>
    <string>${GYDS_BIN}/${BIN_NAME}</string>
    <string>--config</string><string>${GYDS_HOME}/config/devnet.toml</string>
    <string>--chain-id</string><string>${CHAIN_ID}</string>
    <string>--rpc-port</string><string>${RPC_PORT}</string>
    <string>--p2p-port</string><string>${P2P_PORT}</string>
    <string>--datadir</string><string>${GYDS_HOME}/data</string>
  </array>
  <key>RunAtLoad</key><true/>
  <key>KeepAlive</key><true/>
  <key>StandardOutPath</key><string>${GYDS_HOME}/logs/devnode.log</string>
  <key>StandardErrorPath</key><string>${GYDS_HOME}/logs/devnode-err.log</string>
</dict>
</plist>
PLIST
  launchctl load "$PLIST"
  log "launchd service installed: com.gydschain.devnode"
fi

# ─── 7. Summary ──────────────────────────────────────────────────────────────
step "7/7  Done"

echo -e "${CYAN}"
cat <<EOF
╔══════════════════════════════════════════════════════════════════╗
║  GYDSchain Dev Node is installed!                                ║
╠══════════════════════════════════════════════════════════════════╣
║  Chain ID:   ${CHAIN_ID}  (0x343C)                                  ║
║  RPC URL:    http://127.0.0.1:${RPC_PORT}                             ║
║  WS URL:     ws://127.0.0.1:${WS_PORT}                               ║
║  P2P Port:   ${P2P_PORT}                                              ║
║  API Port:   ${API_PORT}                                              ║
║  Block Time: ${BLOCK_TIME}s  (fast devnet)                              ║
║  Data:       ${GYDS_HOME}/data
║  Logs:       ${GYDS_HOME}/logs
╠══════════════════════════════════════════════════════════════════╣
║  START:   sudo systemctl start gyds-devnode   (Linux)            ║
║           launchctl start com.gydschain.devnode  (macOS)         ║
║  LOGS:    journalctl -u gyds-devnode -f       (Linux)            ║
║           tail -f ${GYDS_HOME}/logs/devnode.log (macOS)         ║
╠══════════════════════════════════════════════════════════════════╣
║  Add to MetaMask:                                                ║
║    Network:   GYDS Devnet                                        ║
║    RPC:       http://127.0.0.1:${RPC_PORT}                            ║
║    Chain ID:  ${CHAIN_ID}                                             ║
║    Symbol:    dGYDS                                              ║
╚══════════════════════════════════════════════════════════════════╝
EOF
echo -e "${NC}"
