#!/bin/bash
# GYDS RPC Proxy — nginx reverse proxy for rpc.netlifegy.com
# Proxies rpc.netlifegy.com → localhost:8545 (or any RPC node)
# Usage: bash install-rpc-proxy.sh [--domain rpc.netlifegy.com] [--port 8545]

set -e

DOMAIN="${1:-rpc.netlifegy.com}"
BACKEND_PORT="${BACKEND_PORT:-8545}"
WS_PORT="${WS_PORT:-8546}"
EMAIL="${CERTBOT_EMAIL:-admin@netlifegy.com}"

log() { echo -e "\033[0;36m[RPC Proxy]\033[0m $*"; }
ok()  { echo -e "\033[0;32m✓\033[0m $*"; }
err() { echo -e "\033[0;31m✗\033[0m $*"; exit 1; }

# Parse named args
while [[ "$#" -gt 0 ]]; do
    case $1 in
        --domain)       DOMAIN="$2"; shift ;;
        --port)         BACKEND_PORT="$2"; shift ;;
        --ws-port)      WS_PORT="$2"; shift ;;
        --email)        EMAIL="$2"; shift ;;
        *) echo "Unknown: $1"; exit 1 ;;
    esac
    shift
done

log "Installing GYDS RPC Proxy"
log "Domain      : $DOMAIN"
log "Backend RPC : localhost:$BACKEND_PORT"
log "Backend WS  : localhost:$WS_PORT"

command -v nginx    >/dev/null 2>&1 || { apt-get update -qq && apt-get install -y nginx; }
command -v certbot  >/dev/null 2>&1 || { apt-get install -y certbot python3-certbot-nginx; }

CONF="/etc/nginx/sites-available/${DOMAIN}"

cat > "$CONF" << EOF
# GYDS RPC Proxy — generated by install-rpc-proxy.sh
# HTTP → redirect to HTTPS (certbot will add SSL block)
server {
    listen 80;
    server_name ${DOMAIN};

    # Rate limiting: 100 req/s per IP for RPC calls
    limit_req_zone \$binary_remote_addr zone=gyds_rpc:10m rate=100r/s;

    location / {
        limit_req zone=gyds_rpc burst=200 nodelay;

        # CORS headers for MetaMask / ethers.js
        add_header Access-Control-Allow-Origin  "*" always;
        add_header Access-Control-Allow-Methods "GET, POST, OPTIONS" always;
        add_header Access-Control-Allow-Headers "Content-Type, Authorization, X-API-Key" always;
        add_header X-Chain-ID "198282" always;

        if (\$request_method = OPTIONS) {
            add_header Content-Length 0;
            add_header Content-Type text/plain;
            return 204;
        }

        # Only allow POST JSON-RPC and GET status
        proxy_pass http://127.0.0.1:${BACKEND_PORT};
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_read_timeout 30s;
        proxy_connect_timeout 5s;

        # Block non-RPC paths
        proxy_intercept_errors on;
    }

    # WebSocket upgrade for ws.netlifegy.com style routing
    location /ws {
        proxy_pass http://127.0.0.1:${WS_PORT};
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host \$host;
        proxy_read_timeout 3600s;
    }
}
EOF

# Enable site
ln -sf "$CONF" "/etc/nginx/sites-enabled/${DOMAIN}" 2>/dev/null || true

# Test config
nginx -t || err "nginx config test failed — check $CONF"
systemctl reload nginx
ok "nginx reloaded"

# Get SSL cert
log "Requesting SSL certificate from Let's Encrypt..."
certbot --nginx -d "$DOMAIN" --non-interactive --agree-tos -m "$EMAIL" || {
    log "Certbot failed — ensure DNS for $DOMAIN points to this server's IP"
    log "Run manually: certbot --nginx -d $DOMAIN -m $EMAIL"
}

echo ""
echo "======================================================"
echo " GYDS RPC Proxy ready!"
echo "======================================================"
echo " HTTP RPC   : https://${DOMAIN}"
echo " WebSocket  : wss://${DOMAIN}/ws"
echo " Chain ID   : 198282"
echo " Backend    : localhost:${BACKEND_PORT}"
echo ""
echo " MetaMask setup:"
echo "   Network Name  : GYDSchain"
echo "   RPC URL       : https://${DOMAIN}"
echo "   Chain ID      : 198282"
echo "   Symbol        : GYDS"
echo "======================================================"
